name: Format

permissions:
  checks: write
  contents: write

on:
  push:
    branches:

jobs:
  format:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run format
        run: npm run format

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Format by GitHub Actions"
          git push origin HEAD:main
